# Generated by Django 3.1.3 on 2021-01-19 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=264)),
                ('eventDescription', models.TextField()),
                ('eventVenue', models.CharField(max_length=50)),
                ('eventDate', models.DateField()),
                ('eventTime', models.TimeField()),
                ('eventSpeaker', models.CharField(max_length=50)),
                ('numAttendees', models.IntegerField()),
            ],
        ),
    ]
