# Generated by Django 3.1.3 on 2021-01-21 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventreg', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventdata',
            name='id',
        ),
        migrations.RemoveField(
            model_name='eventdata',
            name='numAttendees',
        ),
        migrations.AlterField(
            model_name='eventdata',
            name='eventName',
            field=models.CharField(max_length=264, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='eventdata',
            name='eventSpeaker',
            field=models.TextField(),
        ),
    ]
