# Generated by Django 3.1.3 on 2021-01-23 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventreg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdata',
            name='eventName',
            field=models.CharField(max_length=264, unique=True),
        ),
    ]
