# Generated by Django 3.1.7 on 2021-07-26 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventreg", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventuserdata",
            name="studentName",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="eventuserdata",
            name="studentReg",
            field=models.CharField(max_length=12),
        ),
    ]
