# Generated by Django 3.1.3 on 2021-01-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventreg', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventdata',
            name='numAttendees',
        ),
        migrations.AlterField(
            model_name='eventdata',
            name='eventSpeaker',
            field=models.TextField(),
        ),
    ]
