# Generated by Django 3.1.7 on 2021-08-27 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventreg', '0002_auto_20210726_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='eventIsLive',
            field=models.BooleanField(default=True),
        ),
    ]
