# Generated by Django 3.1.3 on 2021-01-23 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventreg', '0002_auto_20210123_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdata',
            name='eventURL',
            field=models.URLField(default=None),
            preserve_default=False,
        ),
    ]
