# Generated by Django 3.1.3 on 2021-01-23 11:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eventreg', '0004_eventuserdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdata',
            name='eventRegEndDate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventdata',
            name='eventRegEndTime',
            field=models.DateField(default=datetime.datetime(2021, 1, 23, 11, 48, 50, 118053, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
