# Generated by Django 3.0.7 on 2021-01-28 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventreg', '0005_auto_20210123_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=264, unique=True)),
                ('eventDescription', models.TextField()),
                ('eventVenue', models.CharField(max_length=50)),
                ('eventDate', models.DateField()),
                ('eventStartTime', models.TimeField(default='20:00')),
                ('eventEndTime', models.TimeField(default='20:00')),
                ('eventRegEndDate', models.DateField()),
                ('eventRegEndTime', models.DateField()),
                ('eventSpeaker', models.TextField()),
                ('eventURL', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='eventuserdata',
            name='eventName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventreg.Event'),
        ),
        migrations.DeleteModel(
            name='EventData',
        ),
    ]
