# Generated by Django 3.1.3 on 2021-02-03 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventreg', '0006_auto_20210131_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='eventDocumentation',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventLogo',
            field=models.ImageField(upload_to='EventBanner/'),
        ),
    ]
