# Generated by Django 3.0.7 on 2021-02-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventreg', '0006_auto_20210128_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eventRegEndTime',
            field=models.TimeField(default='20:00'),
        ),
    ]
