# Generated by Django 3.1.3 on 2021-02-07 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventreg', '0007_auto_20210203_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eventRegEndTime',
            field=models.TimeField(default='20:00'),
        ),
    ]
