# Generated by Django 3.0.7 on 2021-02-08 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventreg', '0007_auto_20210203_1241'),
        ('eventreg', '0007_auto_20210207_2140'),
    ]

    operations = [
    ]
